/**
 * Apex Ecosystem Marketing Platform - Real Project Data Registry with Bilingual (EN & AR) Support
 */

window.ECOSYSTEM_PROJECTS = [
  {
    id: 'stttts',
    title: 'Voice Converter - Speech Studio',
    subtitle: 'Web Speech STT, Neural TTS & 3D WebGL Agent',
    arabicTitle: 'استوديو الصوت - تحويل الكلام',
    arabicSubtitle: 'تحويل الكلام إلى نصوص وتخليق الصوت العصبي',
    category: 'ai',
    categoryLabel: 'Speech & WebGL AI',
    path: './STT_TTS/index.html',
    icon: 'fa-microphone-lines',
    color: '#9d4edd',
    glowColor: 'rgba(157, 78, 221, 0.6)',
    rating: 99,
    metrics: { aiScore: 99, engagement: 96, graphics: 94, utility: 99 },
    description: 'Dual-engine speech studio featuring real-time Web Speech API transcription, customizable neural Text-to-Speech (voice selection, speed 0.5x-2.0x, pitch sliders), and a Three.js 3D Agent Core (agent.js) with emissive icosahedron meshes.',
    arabicDescription: 'استوديو الصوت المزدوج لتحويل الكلام إلى نصوص تفاعلية وتخليق الأصوات الاصطناعية مع مجسم ثلاثي الأبعاد متفاعل.',
    features: ['Web Speech STT Engine', 'Custom Voice/Pitch/Speed TTS', 'Three.js 3D Icosahedron Agent', 'Real-Time State Transitions'],
    tags: ['Web Speech API', 'Three.js 3D Agent', 'Audio Engine', 'Speech Synth'],
    position: { x: 0, y: 3, z: 0 },
    orbitRadius: 0,
    size: 2.2
  },
  {
    id: 'stockmarket',
    title: 'StockDash Market Terminal',
    subtitle: 'Real-Time Ticker Search & 3D Sentiment Globe',
    arabicTitle: 'منصة ستوك داش المالية',
    arabicSubtitle: 'تحليلات أسهم فورية وكرة مشاعر السوق',
    category: 'finance',
    categoryLabel: 'Finance & WebGL',
    path: './stock market/index.html',
    icon: 'fa-chart-line',
    color: '#00ffe1',
    glowColor: 'rgba(0, 255, 225, 0.6)',
    rating: 98,
    metrics: { aiScore: 92, engagement: 95, graphics: 98, utility: 96 },
    description: 'Institutional-grade financial terminal with real-time stock ticker search (AAPL, GOOGL, MSFT, AMZN, TSLA), D3.js historical price area/line charts (1M/6M/1Y range toggles), and a Three.js 3D Market Sentiment Globe.',
    arabicDescription: 'منصة سوق الأسهم المالية للبحث عن الأسهم ومتابعة الرسوم البيانية التفاعلية بمكتبة دي ثري وكرة مشاعر السوق ثلاثية الأبعاد.',
    features: ['D3.js Stock Price History', '1M/6M/1Y Timeframe Toggles', 'Three.js 3D Sentiment Globe', 'Top Movers Data Table'],
    tags: ['Stock Market', 'D3.js Charts', 'Three.js Globe', 'Bootstrap 5'],
    position: { x: 7, y: 1.5, z: 4 },
    orbitRadius: 8,
    size: 1.8
  },
  {
    id: 'dashboard',
    title: 'GeoDash - Global Insights',
    subtitle: 'D3.js v7 Analytics & REST Countries API Data',
    arabicTitle: 'جيو داش - البيانات العالمية',
    arabicSubtitle: 'تحليلات سكانية وجغرافية بمكتبة دي ثري',
    category: 'finance',
    categoryLabel: 'Finance & Analytics',
    path: './dashboard/index.html',
    icon: 'fa-globe-americas',
    color: '#3a86ff',
    glowColor: 'rgba(58, 134, 255, 0.6)',
    rating: 96,
    metrics: { aiScore: 85, engagement: 92, graphics: 90, utility: 98 },
    description: 'Executive geographic and demographic data dashboard fetching real-time data from REST Countries API. Features D3.js Top 10 Population bar chart, regional distribution donut chart, and area vs population density scatter plot.',
    arabicDescription: 'لوحة تحليلات البيانات الجغرافية والسكانية العالمية المربوطة بواجهة بيانات دول العالم ومخططات دي ثري البيانية.',
    features: ['REST Countries Live API', 'D3.js Bar/Donut/Scatter Charts', 'Real-Time Population KPIs', 'Multi-Tab View Navigator'],
    tags: ['D3.js v7', 'REST Countries API', 'Demographics', 'Data Viz'],
    position: { x: -8, y: -1, z: 5 },
    orbitRadius: 9.5,
    size: 1.7
  },
  {
    id: 'todolist',
    title: '3D Dynamic To-Do List',
    subtitle: 'Three.js Particle Canvas & D3 Progress Ring',
    arabicTitle: 'قائمة المهام ثلاثية الأبعاد',
    arabicSubtitle: 'إدارة المهام التفاعلية ومؤشر التقدم',
    category: 'productivity',
    categoryLabel: 'Productivity Suite',
    path: './todolist/index.html',
    icon: 'fa-list-check',
    color: '#7000ff',
    glowColor: 'rgba(112, 0, 255, 0.6)',
    rating: 96,
    metrics: { aiScore: 86, engagement: 93, graphics: 94, utility: 98 },
    description: 'Spatial task manager featuring a Three.js interactive particle background with floating spheres, a D3.js completion progress donut ring, priority matrix (High/Medium/Low), task category tagging, and localStorage persistence.',
    arabicDescription: 'تطبيق إدارة المهام التفاعلي بخلفية الجزيئات ثلاثية الأبعاد وحلقة تقدم الإنجاز البيانية وتصنيف الأولويات.',
    features: ['Three.js Particle Canvas', 'D3 Progress Donut Ring', 'Priority & Category Matrix', 'LocalStorage Persistence'],
    tags: ['Task Manager', 'Three.js Scene', 'D3 Charts', 'Bootstrap 5'],
    position: { x: 6, y: -3, z: -6 },
    orbitRadius: 11,
    size: 1.7
  },
  {
    id: 'weather',
    title: 'Modern Weather App',
    subtitle: 'Live Geo Cascading Search & Micro-Forecasts',
    arabicTitle: 'تطبيق الطقس الحديث',
    arabicSubtitle: 'متابعة درجات الحرارة والرياح في مدن العالم',
    category: 'productivity',
    categoryLabel: 'Productivity Suite',
    path: './waetehr app/index.html',
    icon: 'fa-cloud-sun-rain',
    color: '#00b4d8',
    glowColor: 'rgba(0, 180, 216, 0.6)',
    rating: 93,
    metrics: { aiScore: 82, engagement: 91, graphics: 89, utility: 96 },
    description: 'Real-time weather forecast tracking application with cascading country and city selectors, dynamic condition icon rendering, temperature (°C), humidity percentage, wind speed telemetry, and error handling.',
    arabicDescription: 'تطبيق متابعة حالة الطقس ودرجات الحرارة الفورية ورطوبة الجو وسرعة الرياح في جميع مدن العالم.',
    features: ['Cascading Country/City Selectors', 'Live Weather Telemetry', 'Dynamic Condition Icons', 'Humidity & Wind Speed'],
    tags: ['Weather API', 'Geo Selectors', 'Forecast', 'FontAwesome'],
    position: { x: -7, y: 4, z: -5 },
    orbitRadius: 10,
    size: 1.6
  },
  {
    id: 'recipe',
    title: 'Culinary Explorer',
    subtitle: 'Searchable Recipe Engine & Cooking Steps',
    arabicTitle: 'مستكشف الطهي والوصفات',
    arabicSubtitle: 'البحث عن أشهى المأكولات والمكونات',
    category: 'productivity',
    categoryLabel: 'Productivity Suite',
    path: './recipe/index.html',
    icon: 'fa-utensils',
    color: '#ffb703',
    glowColor: 'rgba(255, 183, 3, 0.6)',
    rating: 91,
    metrics: { aiScore: 88, engagement: 89, graphics: 88, utility: 94 },
    description: 'Curated recipe discovery portal featuring real-time recipe and ingredient search, dynamic recipe cards grid, step-by-step cooking instruction views, detailed ingredient breakdowns, and loader states.',
    arabicDescription: 'منصة استكشاف وصفات الطعام العالمية والبحث عن المكونات وطرق التحضير خطوة بخطوة.',
    features: ['Ingredient & Dish Search', 'Dynamic Recipe Cards Grid', 'Detailed Cooking Instructions', 'Interactive Ingredients Modal'],
    tags: ['Recipe API', 'Culinary Search', 'Glassmorphic Header', 'Food'],
    position: { x: 11, y: 1, z: -3 },
    orbitRadius: 12,
    size: 1.6
  },
  {
    id: 'chameleon',
    title: 'Image Compositor Pro',
    subtitle: 'HTML5 Canvas Image Stamping & Rotation Engine',
    arabicTitle: 'محرر ومدمج الصور المتقدم',
    arabicSubtitle: 'دمج وتدوير وتقليص الصور على الكانفاس',
    category: 'games',
    categoryLabel: 'Interactive Tools',
    path: './find the chameleon/index.html',
    icon: 'fa-sliders',
    color: '#06d6a0',
    glowColor: 'rgba(6, 214, 160, 0.6)',
    rating: 92,
    metrics: { aiScore: 75, engagement: 98, graphics: 92, utility: 95 },
    description: 'High-performance HTML5 canvas image editing utility allowing users to upload background & overlay photos, scale (1-200%), rotate (-180° to 180°), adjust X/Y positioning and opacity, stamp overlay, and download high-res PNG outputs.',
    arabicDescription: 'محرر الصور عالي الأداء لتعديل وتحجيم وتدوير الصور ودمجها وتصديرها بصيغة عالية الدقة.',
    features: ['HTML5 Canvas Rendering', 'Image Scale & Angle Control', 'Position X/Y & Opacity Sliders', 'High-Res PNG Export'],
    tags: ['Canvas Processing', 'Image Editing', 'Glassmorphism', 'Export'],
    position: { x: -11, y: -2, z: -7 },
    orbitRadius: 13.5,
    size: 1.6
  },
  {
    id: 'tictactoe',
    title: '3D Tic Tac Toe',
    subtitle: 'Three.js WebGL Grid & GSAP Animations',
    arabicTitle: 'لعبة إكس أو ثلاثية الأبعاد',
    arabicSubtitle: 'محرك ألعاب ثلاثي الأبعاد ومؤثرات جيساب',
    category: 'games',
    categoryLabel: 'Interactive Games',
    path: './TIC TAC TOC/index.html',
    icon: 'fa-gamepad',
    color: '#ff0055',
    glowColor: 'rgba(255, 0, 85, 0.6)',
    rating: 90,
    metrics: { aiScore: 70, engagement: 94, graphics: 92, utility: 75 },
    description: 'Futuristic WebGL board game built with Three.js and GSAP 3.12 animations. Features raycasted 3D grid cell clicks, 3D X & O mesh instantiations, smooth GSAP scaling animations, turn indicators, and winning line detection.',
    arabicDescription: 'لعبة إكس أو ثلاثية الأبعاد التفاعلية بمحرك ثري دوت جي إس ومؤثرات الحركة الفائقة.',
    features: ['Three.js 3D Game Geometry', 'GSAP 3.12 Smooth Scaling', 'Raycasted 3D Board Controls', 'Winning Detection Engine'],
    tags: ['Three.js Game', 'GSAP Animation', 'Raycasting', '3D Gaming'],
    position: { x: 12, y: -4, z: 6 },
    orbitRadius: 14,
    size: 1.6
  },
  {
    id: 'portfolio',
    title: 'Premium Developer Portfolio',
    subtitle: 'Typewriter Animation & Glassmorphism Showcase',
    arabicTitle: 'معرض الأعمال المتقدم',
    arabicSubtitle: 'مؤثرات كتابة تفاعلية واستعراض مهارات المطور',
    category: 'enterprise',
    categoryLabel: 'Enterprise & Portfolio',
    path: './protofilo/index.html',
    icon: 'fa-user-ninja',
    color: '#ff007f',
    glowColor: 'rgba(255, 0, 127, 0.6)',
    rating: 95,
    metrics: { aiScore: 80, engagement: 90, graphics: 95, utility: 90 },
    description: 'State-of-the-art developer portfolio featuring a custom glowing cursor (dot + outline), typewriter title animation, glassmorphic hero cards, skill badges (HTML5, CSS3, JS, React, Node.js, UI/UX), project showcase grid, and contact form.',
    arabicDescription: 'موقع معرض الأعمال الشخصي المتقدم مع المؤشر المضيء ومؤثرات الآلة الكاتبة وبطاقات المهارات والمشاريع.',
    features: ['Typewriter Headline Engine', 'Custom Dual-Cursor System', 'Glassmorphism Design System', 'Skill Tags & Project Grid'],
    tags: ['Developer Portfolio', 'Typewriter Effect', 'Glassmorphism', 'UI/UX'],
    position: { x: -13, y: 3, z: 4 },
    orbitRadius: 15,
    size: 1.6
  },
  {
    id: 'company',
    title: 'Nexus - Innovation',
    subtitle: 'Multi-Lingual i18n & Three.js Canvas Header',
    arabicTitle: 'شركة نكسس للابتكار',
    arabicSubtitle: 'موقع مؤسسي متعدد اللغات وخلفية ثلاثية الأبعاد',
    category: 'enterprise',
    categoryLabel: 'Enterprise & Portfolio',
    path: './company/index.html',
    icon: 'fa-building',
    color: '#00f3ff',
    glowColor: 'rgba(0, 243, 255, 0.6)',
    rating: 94,
    metrics: { aiScore: 70, engagement: 88, graphics: 85, utility: 95 },
    description: 'Corporate web application with Bootstrap 5, Three.js 3D background canvas header, multi-lingual internationalization i18n dropdown (English, Français, Español, Arabic), dark/light theme switcher, and stat counter cards.',
    arabicDescription: 'الموقع المؤسسي المتكامل متعدد اللغات المربوط بخلفية ثلاثية الأبعاد تفاعلية وتصميم زجاجي أنيق.',
    features: ['Multi-Lingual i18n Engine (EN/FR/ES/AR)', 'Three.js Hero Background', 'Dark / Light Mode Toggle', 'Bootstrap 5 Glass Layout'],
    tags: ['Corporate', 'Multi-Lingual i18n', 'Three.js Canvas', 'Bootstrap 5'],
    position: { x: 5, y: 5, z: -9 },
    orbitRadius: 16,
    size: 1.6
  }
];

window.ECOSYSTEM_CATEGORIES = [
  { id: 'all', label: 'All Projects (10)', icon: 'fa-cubes' },
  { id: 'ai', label: 'Speech & WebGL AI', icon: 'fa-brain' },
  { id: 'finance', label: 'Finance & Analytics', icon: 'fa-chart-pie' },
  { id: 'productivity', label: 'Productivity Suite', icon: 'fa-bolt' },
  { id: 'games', label: 'Interactive Games', icon: 'fa-gamepad' },
  { id: 'enterprise', label: 'Enterprise & Portfolio', icon: 'fa-building' }
];
